name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - uses: actions/upload-artifact@v2
      with:
        name: Windows Build
        path: src/dist/windows
  build_lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pyinstaller src/main.py

    - uses: actions/upload-artifact@v2
      with:
        name: Linux Build
        path: src/dist/linux
  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pyinstaller src/main.py

    - uses: actions/upload-artifact@v2
      with:
        name: Mac Build
        path: src/dist/
